.catalog:
  name: "Planning"
  version: "3.14.0.3-SNAPSHOT"
  description: "Planning"
  minimum_rancher_version: v0.46.0
  questions:
    - variable: replset_name
      description: "Name of the MongoDB replicaSet"
      label: "ReplicaSet Name"
      type: "string"
      required: true
      default: "rs0"
database:
  scale: 1
algorithm:
  scale: 1
web:
  scale: 1