.catalog:
  name: "Planning"
  version: "latest"
  description: "Planning"
  minimum_rancher_version: v0.46.0
  questions:
    - variable: PLANNING_DB_JNDI
      description: "Nome JNDI"
      label: "JNDI"
      type: "string"
      required: true
      default: "XSCXPLAN"
database:
  scale: 1
algorithm:
  scale: 1
web:
  scale: 1